# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.1

options:
  size: 2x

pipelines:
  custom:
    phpcs: 
    - step: &shared_phpcs
        name: Phpcs
        image: joomunited/phpcs
        script:
        - ln -s /root/.composer/vendor $BITBUCKET_CLONE_DIR/vendor
        - phpcs -s .
    codeception_core_install:
    - step: &shared_codeception_core_install
        name: CC WP latest core install
        image: joomunited/codeception
        script:
        - wait_services.sh
        - export WP_VERSION="latest" && export GUTENBERG_TYPE="core" && export INSTALL_TYPE="install"
        - bash $BITBUCKET_CLONE_DIR/tests/scripts/bitbucket_codeception.sh
        artifacts:
        - tests/_output/**
        services:
        - chromedriver
        - mysql
        - wordpress
    codeception_core_update:
    - step: &shared_codeception_core_update
        name: CC WP latest core update
        image: joomunited/codeception
        script:
        - wait_services.sh
        - export WP_VERSION="latest" && export GUTENBERG_TYPE="core" && export INSTALL_TYPE="update"
        - bash $BITBUCKET_CLONE_DIR/tests/scripts/bitbucket_codeception.sh
        artifacts:
        - tests/_output/**
        services:
        - chromedriver
        - mysql
        - wordpress
    codeception_plugin_install:
    - step: &shared_codeception_plugin_install
        name: CC WP latest plugin install
        image: joomunited/codeception
        script:
        - wait_services.sh
        - export WP_VERSION="latest" && export GUTENBERG_TYPE="plugin" && export INSTALL_TYPE="install"
        - bash $BITBUCKET_CLONE_DIR/tests/scripts/bitbucket_codeception.sh
        artifacts:
        - tests/_output/**
        services:
        - chromedriver
        - mysql
        - wordpress
    codeception_plugin_update:
    - step: &shared_codeception_plugin_update
        name: CC WP latest plugin update
        image: joomunited/codeception
        script:
        - wait_services.sh
        - export WP_VERSION="latest" && export GUTENBERG_TYPE="plugin" && export INSTALL_TYPE="update"
        - bash $BITBUCKET_CLONE_DIR/tests/scripts/bitbucket_codeception.sh
        artifacts:
        - tests/_output/**
        services:
        - chromedriver
        - mysql
        - wordpress
    codeception_51_install:
    - step: &shared_codeception_52_plugin_install
        name: CC WP 5.2 plugin install
        image: joomunited/codeception
        script:
        - wait_services.sh
        - export WP_VERSION="5.2" && export GUTENBERG_TYPE="plugin" && export INSTALL_TYPE="install"
        - bash $BITBUCKET_CLONE_DIR/tests/scripts/bitbucket_codeception.sh
        artifacts:
        - tests/_output/**
        services:
        - chromedriver
        - mysql
        - wordpress52
    codeception_51_update:
    - step: &shared_codeception_52_plugin_update
        name: CC WP 5.2 plugin update
        image: joomunited/codeception
        script:
        - wait_services.sh
        - export WP_VERSION="5.2" && export GUTENBERG_TYPE="plugin" && export INSTALL_TYPE="update"
        - bash $BITBUCKET_CLONE_DIR/tests/scripts/bitbucket_codeception.sh
        artifacts:
        - tests/_output/**
        services:
        - chromedriver
        - mysql
        - wordpress52
    codeception_51_core_install:
      - step: &shared_codeception_52_core_install
          name: CC WP 5.2 core install
          image: joomunited/codeception
          script:
            - wait_services.sh
            - export WP_VERSION="5.2" && export GUTENBERG_TYPE="core" && export INSTALL_TYPE="install"
            - bash $BITBUCKET_CLONE_DIR/tests/scripts/bitbucket_codeception.sh
          artifacts:
            - tests/_output/**
          services:
            - chromedriver
            - mysql
            - wordpress52
    codeception_51_core_update:
      - step: &shared_codeception_52_core_update
          name: CC WP 5.2 core update
          image: joomunited/codeception
          script:
            - wait_services.sh
            - export WP_VERSION="5.2" && export GUTENBERG_TYPE="core" && export INSTALL_TYPE="update"
            - bash $BITBUCKET_CLONE_DIR/tests/scripts/bitbucket_codeception.sh
          artifacts:
            - tests/_output/**
          services:
            - chromedriver
            - mysql
            - wordpress52
    generate_package:
    - step: &shared_generate_package
        name: Create package
        image: joomunited/deployment
        script:
        - git clone git@bitbucket.org:junited/deployment-scripts.git deployment
        - cp -r /root/.composer/vendor $BITBUCKET_CLONE_DIR/deployment/vendor
        - php $BITBUCKET_CLONE_DIR/deployment/replacement.php
        - php $BITBUCKET_CLONE_DIR/deployment/wordpress_language_extractor.php
        - php $BITBUCKET_CLONE_DIR/deployment/zip_package.php
        - bash $BITBUCKET_CLONE_DIR/deployment/upload_latest_commit.sh
        artifacts:
        - deployment/package.zip
    update_changelog:
    - step: &shared_update_changelog
        name: Update Joomunited changelog
        image: joomunited/deployment
        script:
        - git clone git@bitbucket.org:junited/deployment-scripts.git deployment
        - cp -r /root/.composer/vendor $BITBUCKET_CLONE_DIR/deployment/vendor
        - php $BITBUCKET_CLONE_DIR/deployment/replacement.php
        - php $BITBUCKET_CLONE_DIR/deployment/joomunited_changelog.php --username $ADMIN_USERNAME --password $ADMIN_PASSWORD --article_id $CHANGELOG_ARTICLE_ID
    deployment_production:
    - step: &shared_deployment_production
        name: Publish to production
        image: joomunited/deployment
        deployment: production
        script:
        - git clone git@bitbucket.org:junited/deployment-scripts.git deployment
        - bash $BITBUCKET_CLONE_DIR/deployment/validate_pipeline_branch.sh master
        - cp -r /root/.composer/vendor $BITBUCKET_CLONE_DIR/deployment/vendor
        - php $BITBUCKET_CLONE_DIR/deployment/replacement.php
        - php $BITBUCKET_CLONE_DIR/deployment/wordpress_language_extractor.php
        - php $BITBUCKET_CLONE_DIR/deployment/zip_package.php
        - php $BITBUCKET_CLONE_DIR/deployment/joomunited_changelog.php --username $ADMIN_USERNAME --password $ADMIN_PASSWORD --article_id $CHANGELOG_ARTICLE_ID
        - php $BITBUCKET_CLONE_DIR/deployment/language_uploader.php --username $ADMIN_USERNAME --password $ADMIN_PASSWORD --language_id $LANGUAGE_ID --language_extension_id $LANGUAGE_EXTENSION_ID
        - bash $BITBUCKET_CLONE_DIR/deployment/svn_updater.sh
        - bash $BITBUCKET_CLONE_DIR/deployment/upload_tagged_version.sh
        - bash $BITBUCKET_CLONE_DIR/deployment/tag.sh
        artifacts:
        - deployment/package.zip
  branches:
    'development':
    - parallel:
      - step: *shared_phpcs
      - step: *shared_generate_package
    'release/*':
    - parallel:
      - step: *shared_phpcs
#      - step: *shared_codeception_51_core_install
#      - step: *shared_codeception_51_core_update
#      - step: *shared_codeception_51_plugin_install
#      - step: *shared_codeception_51_plugin_update
      - step: *shared_codeception_52_core_install
      - step: *shared_codeception_52_core_update
      - step: *shared_codeception_52_plugin_install
      - step: *shared_codeception_52_plugin_update
      - step: *shared_codeception_core_install
      - step: *shared_codeception_core_update
      - step: *shared_codeception_plugin_install
      - step: *shared_codeception_plugin_update
      - step: *shared_generate_package
    'master':
    - step: *shared_deployment_production

definitions:
  services:
    chromedriver:
      image: joomunited/chromedriver:latest
    mysql:
      image: mysql:5.7.22
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    wordpress:
      image: joomunited/wordpress_cgi:latest
    wordpress52:
      image: joomunited/wordpress_cgi:5.2
    wordpress51:
      image: joomunited/wordpress_cgi:5.1